CREATE OR REPLACE NONEDITIONABLE TRIGGER ALTERA_PARC
BEFORE UPDATE ON PRC_PARCEIRO
FOR EACH ROW

BEGIN
  DECLARE
  ID_USU INT := :NEW.USU_ALTER;
  V_VALUE VARCHAR(5);
  V_VALUE_1 VARCHAR(5);
   BEGIN
     --CFG_USU_ALT_PARC => USUÁRIO ALTERA CADASTRO DE PARCEIRO?
     SELECT CFG_USU_ALT_PARC INTO V_VALUE FROM CONFIG_USU WHERE COD_USU = ID_USU;

     IF  NVL(V_VALUE,'N') = 'N' THEN
       RAISE_APPLICATION_ERROR(-20303,'Usuário logado não tem permissão para alterar parceiros,favor verificar seus acessos!');
     END IF;
     
     --USUÁRIO DESBLOQUEIA OU BLOQUEIA PARCEIRO?
     SELECT CFG_USU_LIB_BLOQ_PARC INTO V_VALUE_1 FROM CONFIG_USU WHERE COD_USU = ID_USU;
     
     IF UPDATING('PARC_BLOQUEADO') AND  NVL(V_VALUE_1,'N') = 'N' AND :NEW.PARC_BLOQUEADO <> :OLD.PARC_BLOQUEADO THEN
       RAISE_APPLICATION_ERROR(-20304,'Usuário logado não tem permissão para desbloquear/bloquear parceiros,favor verificar seus acessos!');
     END IF;    

   END;
END;
